name: deploy-frontend-to-stage 
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  deploy-to-stage:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check for version change
        id: version_changed
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Build new pkg version
        run: npm run build

      - name: Publish to NPM
        if: steps.version_changed.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: discord
        uses: sebastianpopp/discord-action@releases/v2
        with: 
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: $ {{ github.actor }} has successfylly published new pkg version.
